arm:
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  #kdl_kinematics_plugin/KDLKinematicsPlugin
  #
  solve_type: Speed
  kinematics_solver_search_resolution: 0.0001
  kinematics_solver_timeout: 0.005
