mz07:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100000

  mz07_controller:
    type: position_controllers/JointTrajectoryController #TODO
    joints:
      - J1
      - J2
      - J3
      - J4
      - J5
      - J6
    gains: # required if using effort_interface, not necessary if using position_interface
      J1: { p: 1000.0, i: 500.0, d: 10.0, i_clamp: 100.0 }
      J2: { p: 1000.0, i: 500.0, d: 10.0, i_clamp: 200.0 }
      J3: { p: 1000.0, i: 500.0, d: 20.0, i_clamp: 100.0 }
      J4: { p: 200.0, i: 10.0, d: 0.0, i_clamp: 10.0 }
      J5: { p: 100.0, i: 10.0, d: 0.0, i_clamp: 10.0 }
      J6: { p: 100.0, i: 10.0, d: 0.0, i_clamp: 10.0 }
